import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <div>
      <div>
        <title>마지막 과제</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>
    </div>
  );
};

export default Home;
